pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    exclude:
    - '*'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PowerShell@2
  displayName: Start sqllocaldb instance
  inputs:
    targetType: inline
    script: >
        sqllocaldb start MSSQLLocalDB
        
        
        
        sqllocaldb info MSSQLLocalDB

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: |
     **\*Tests*.csproj
    arguments: '--configuration DbTest'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/webapps'
    zipAfterPublish: True
